### PR TITLE
Fix: Display full changelog

### LINKED ISSUE #825: Extension browser changelog doesn't show up in the site
https://webhint.io/about/changelog/ for September 12th there should be a changelog of the extension-browser.

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/webhint.io)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

## Short description of the change(s)

The project had different versions of the same package because of how
hoisting works, `hint`'s `optionalDependencies` (the configurations are
not the latest ones) and how npm handles duplicates and `package-lock.json`.
By removing `package-lock.json` npm will always go fetch the latest
version of the packages and avoid these issues. Also all packages will
be installed in `node_modules` and not inside another folder under it.

Because multiple versions of the same package, the changelog was not
always accurate.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Fix #825

### CODE REVIEW

File: helpers/update-site/documentation.js [hunk 1]
```diff
@@ -725,7 +725,8 @@ const createHintCategories = (files) => {
 };
 
 const updateChangelog = async () => {
-    const files = await globby([`${constants.dirs.NODE_MODULES}/{hint,vscode-webhint,@hint/{${resources.join(',')},configuration-all/node_modules/{vscode-webhint,@hint/{${resources.join(',')}}}-*}}/CHANGELOG.md`]);
+    /** All packages should be hoisted so no need to look inside `configuration-all` */
+    const files = await globby([`${constants.dirs.NODE_MODULES}/{hint,vscode-webhint,@hint/{${resources.join(',')}}-*}/CHANGELOG.md`]);
```
Comment (antross) [inline helpers/update-site/documentation.js]: I think there are a couple of more places that use a similar globby pattern that should be updated.

Comment (molant) [reply helpers/update-site/documentation.js]: I've updated the regex everywhere.

File: helpers/update-site/documentation.js [hunk 2]
```diff
@@ -169,14 +171,14 @@ const getResourcesFiles = async () => {
     const imageFiles = [];
 
     for (const resource of resources) {
-        const images = await globby([`${constants.dirs.NODE_MODULES}/{vscode-webhint,@hint/${resource}-*,@hint/configuration-all/node_modules/{vscode-webhint,@hint/${resource}-*}}/images/**/*`], { absolute: true });
+        const images = await globby([`${documentationGlobbyPattern}/images/**/*`], { absolute: true });
```
Comment (antross) [inline helpers/update-site/documentation.js]: This will now match the `hint` package whereas it didn't before. Is that intended or do we need to exclude `hint` either in the pattern or the results to avoid picking up extra resources?

File: helpers/update-site/documentation.js [hunk 3]
```diff
@@ -169,14 +171,14 @@ const getResourcesFiles = async () => {
...
 
         images.forEach((image) => {
             imageFiles.push(getImageItemFromResource(image, resource));
         });
     }
 
-    const docs = await globby([`${constants.dirs.NODE_MODULES}/{vscode-webhint,@hint/{${resources.join(',')}}-*,@hint/configuration-all/node_modules/{vscode-webhint,@hint/{${resources.join(',')}}-*}}/{README.md,docs/*.md}`], { absolute: true });
+    const docs = await globby([`${documentationGlobbyPattern}/{README.md,docs/*.md}`], { absolute: true });
```
Comment (antross) [inline helpers/update-site/documentation.js]: Same question here about `hint` being included where it wasn't before.

File: helpers/update-site/documentation.js (hunk 2 above)
Comment (sarvaje) [reply helpers/update-site/documentation.js]: I think we shouldn't match `hint` here. The hint package is processed in another place IIRC.

File: helpers/update-site/documentation.js (hunk 3 above)
Comment (sarvaje) [reply helpers/update-site/documentation.js]: Same as before, `hint` is processed in another part of the code IIRC, because the structure is different.

File: helpers/update-site/documentation.js (hunk 2 above)
Comment (molant) [reply helpers/update-site/documentation.js]: I've tested the process locally and all the documentation is looking good.
Personally I think we can keep it as is.

File: helpers/update-site/documentation.js (hunk 3 above)
Comment (molant) [reply helpers/update-site/documentation.js]: See https://github.com/webhintio/webhint.io/pull/831#discussion_r325832887

File: helpers/update-site/documentation.js (hunk 2 above)
Comment (antross) [reply helpers/update-site/documentation.js]: Works for me if @sarvaje is okay with it.

Comment (sarvaje) [reply helpers/update-site/documentation.js]: Yep, if everything looks good, I'm ok :)
