### PR TITLE
Fix: Category details should use friendly name

### LINKED ISSUE #642: Category details should use friendly name instead of id
For example: https://webhint.io/docs/user-guide/hints/pitfalls/

image

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #642

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/webhint.io)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

### CODE REVIEW

File: helpers/update-site/documentation.js [hunk 1]
```diff
@@ -701,13 +705,19 @@ const createHintCategories = (files) => {
         if (!acc.has(category)) {
             acc.set(category, {
                 description: config.categories[category].description,
-                hints: [hintName],
+                hints: [{
+                    friendlyName: file.frontMatter.title,
```
Comment (antross) [inline helpers/update-site/documentation.js]: Is this pulling from `meta.ts` or `README.md` for the hint?

Comment (sarvaje) [reply helpers/update-site/documentation.js]: I think this is pulling from `README.md`

Comment (sarvaje) [reply helpers/update-site/documentation.js]: That is something that maybe we can think in change when we start using the packages to build the docs
