### PR TITLE
Fix: Build documentation using public packages instead of the repository

### LINKED ISSUE #757: Build website using public packages instead of the repository.

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #757

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/webhint.io)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

### CODE REVIEW

File: helpers/update-site/documentation.js [hunk 1]
```diff
@@ -385,66 +395,46 @@ const getFileInfo = (file) => {
...
+
+    if (meta) {
+        // In multi-hints, the name will change to be hint/subhint.
+        file.name = meta.id;
+        file.category = meta.docs.category;
+    }
 
-    const hintNameRegex = /id:\s*'([^']*)'/;
-    const categoryRegex = /category:\s*Category\.([a-z]*)/;
-    const descriptionRegex = /description:\s*([^\n]*)/;
```
Comment (antross) [inline helpers/update-site/documentation.js]: So happy these aren't needed anymore 🎉

File: helpers/update-site/formatter.js [hunk 2]
```diff
@@ -1,35 +1,44 @@
...
 
+const globby = require('globby');
 const mkdirp = require('mkdirp');
 
 const { copy } = require('./copy');
 const { safeWriteFile } = require('./common');
 const constants = require('./constants');
 
-const FORMATTER_SRC = `${constants.dirs.HINT_PACKAGES}/formatter-html/src`;
+const globbyPattern = 'node_modules/@hint/{,configuration-all/node_modules/@hint/}formatter-html/dist/src';
```
Comment (antross) [inline helpers/update-site/formatter.js]: Is this because we don't know for sure where `@hint/formatter-html` will end up getting installed by `npm`? What about using `require.resolve('@hint/formatter-html') or `require.resolve('@hint/formatter-html/package.json')` to get us close to the root directory for the HTML formatter?

Comment (sarvaje) [reply helpers/update-site/formatter.js]: now that you mention that, `@hint/formatter-html` should be always in node_modules (It is added to dependencies) so there is no need to take into account the "configuration" part.

In this case, `globbyPattern` will be: `const globbyPattern = 'node_modules/@hint/formatter-html/dist/src';`

What do you think? do you still prefer to use `require.resolve`?

Comment (antross) [reply helpers/update-site/formatter.js]: Nah, just referencing the top-level `node_modules` as you suggested is fine.

Comment (sarvaje) [reply helpers/update-site/formatter.js]: done!
