### PR TITLE
Fix: A11y reported by aXe with `aria-hidden`

### LINKED ISSUE #664: Remove aria-hidden=true from main nav [0.1]
axe is returning the following hints when we run the staged version of the site against webhint: 

```
line 1  col 4374  Error  ARIA hidden element must not contain focusable elements  axe
line 1  col 4832  Error  ARIA hidden element must not contain focusable elements  axe
```

This applies to the main navigation. We have two menu items that are hiding their submenus: "documentation" and "about" via aria-hidden="true" and then when a user clicks on either of those buttons, the submenu is shown by changing the value to aria-hidden="false".

This is triggering the aXe hint because the submenu items are focusable. 

```
<ul role="group" id="submenu-docs" class="navbar__submenu" aria-hidden="true">
<li><a href="/docs/contributor-guide/">Contributor Guide</a></li>  
<li><a href="/docs/user-guide/hints/">Hints</a></li>  
<li><a href="/docs/user-guide/">User Guide</a></li>  
</ul>
```

We need to remove aria-hidden completely from both `ul` submenus and replace with `hidden`. When the user clicks on the main nav button or tabs into the nav via keyboard and hits enter on "documentation" or "about" we need to remove `hidden` so that the submenu will appear. 

@sarvaje I need your assistance with this as I believe this requires JavaScript.

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/webhint.io)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

## Short description of the change(s)

Fix #664

### CODE REVIEW

File: src/webhint-theme/source/components/treeview/treeview.js [hunk 1]
```diff
@@ -169,12 +169,12 @@
 
     var toggleExpandMobileMenu = function (evt) {
         var menu = evt.currentTarget.querySelector('#mobile-toc-submenu');
-        var isClosed = menu.getAttribute('aria-hidden') === 'true';
+        var isClosed = menu.getAttribute('hidden') === '';
```
Comment (antross) [inline src/webhint-theme/source/components/treeview/treeview.js]: For boolean attributes any value is effectively `true`, even if I write `hidden="hidden"`.
```suggestion
        var isClosed = menu.hasAttribute('hidden');
```

File: src/webhint-theme/source/core/css/navigation.css [hunk 2]
```diff
@@ -165,10 +165,6 @@ button.mobile-search-button {
     background-size: 2rem;
 }
 
-[aria-hidden=true] {
-    display: none;
-}
```
Comment (antross) [inline src/webhint-theme/source/core/css/navigation.css]: What's the browser support matrix for the website? I ask because `hidden` support was introduced in IE11. If we are trying to support anything prior to that we may want to change this to:
```css
[hidden] {
    display: none;
}
```

Comment (molant) [reply src/webhint-theme/source/core/css/navigation.css]: We can probably add this piece of code then.
