### PR TITLE
Fix: Documentation is blank for hints with in hint sets

### LINKED ISSUE #617: Documentation is blank for hints within hint sets (e.g. TypeScript configuration) [2.4]
See https://webhint.io/docs/user-guide/hints/hint-typescript-config/

That page renders, but each of the hints pages beneath it is empty:
https://webhint.io/docs/user-guide/hints/hint-typescript-config/import-helpers/

### PR DESCRIPTION
**Pull request by sarvaje**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/webhint.io)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

## Short description of the change(s)

This commit also contain a refactor for how we generate the
documentation in the website.

Fix #617

### CODE REVIEW

**Comment by sarvaje** [comment]
@molant @antross this is not finish yet, but I would like to know your opinion about the refactoring.

File: helpers/update-site.js [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+// 8. Remove cloned repository
+remove(constants.dirs.REPOSITORY, '-rf');
+
+const docFiles = globby.sync(['**/*.md', '!404.md', '!about.md', '!contributors.md', '!docs/index.md'], {
+    absolute: true,
+    cwd: path.join(process.cwd(), constants.dirs.CONTENT)
+});
+
+// 9. Add frontMatter info to documentation.
+addFrontMatter(docFiles)
```
Comment (molant) [inline helpers/update-site.js]: I thought `await` worked on top level with the latest versions of node :/

File: helpers/update-site/constants.js [hunk 2]
```diff
@@ -0,0 +1,40 @@
+const CONTENT = 'src/content';
+const THEME = 'src/webhint-theme';
+const USER_GUIDE = `${CONTENT}/docs/user-guide`;
+const REPOSITORY = require('../mktemp')();
+
+const dirs = {
+    // About documentation destination directory.
```
Comment (molant) [inline helpers/update-site/constants.js]: Nit: Change to `/** */` comment style to get intellisense

Comment (sarvaje) [reply helpers/update-site/constants.js]: done!

File: helpers/update-site.js (hunk 1 above)
Comment (sarvaje) [reply helpers/update-site.js]: At least VSCode show me an error if I try it.

File: helpers/update-site/copy.js [hunk 3]
```diff
@@ -0,0 +1,132 @@
+const fs = require('fs');
+
+const shell = require('shelljs');
+const mkdirp = require('mkdirp');
+
+const constans = require('./constants');
```
Comment (antross) [inline helpers/update-site/copy.js]: Typo: `constans` -> `constants`

File: helpers/update-site/remove.js [hunk 4]
```diff
@@ -0,0 +1,46 @@
+const shell = require('shelljs');
+
+const constans = require('./constants');
```
Comment (antross) [inline helpers/update-site/remove.js]: Typo: `constans` -> `constants`

File: helpers/update-site/resources.js [hunk 5]
```diff
@@ -0,0 +1,318 @@
+const fs = require('fs');
+const path = require('path');
+
+const _ = require('lodash');
+const mkdirp = require('mkdirp');
+const os = require('os');
+const shell = require('shelljs');
+const yamlLoader = require('js-yaml');
+
+const constans = require('./constants');
```
Comment (antross) [inline helpers/update-site/resources.js]: Typo: `constans` -> `constants`

File: helpers/update-site/resources.js [hunk 6]
```diff
@@ -0,0 +1,318 @@
...
+    }, []);
+
+    return { categories: processedCategories };
+};
+
+const generateHintCategoryDocAndInfo = () => {
+    const configDir = path.resolve(__dirname, '..', '..', '_config.yml');
+    const hexoConfig = yamlLoader.safeLoad(fs.readFileSync(configDir, 'utf8')); // eslint-disable-line no-sync
+    /*
+     * We are reading the metadata information directly from the TS files using regex.
```
Comment (antross) [inline helpers/update-site/resources.js]: Not blocking, but since we're doing this should we consider getting the user-friendly display name from here as well instead of from `README.md`? My only hesitation is due to multi-hints since there isn't metadata for the group, but I'd be curious to hear your thoughts.

Comment (sarvaje) [reply helpers/update-site/resources.js]: Yes, but right know, the user-friendly display is not calculated here, is done in another "task" later in the build process. That means, that we should read a couple of times the file to get later the title.

Once that said, I like the idea of taking the name from the metadata too. If you and @molant are ok, I can dedicate more time to this to try to make it a littler bit better.

Comment (molant) [reply helpers/update-site/resources.js]: I'm ok dedicanting more time

**Comment by molant** [comment]
> do we have this hosted on a staging area somewhere so we can try it out before going live?

Fetching from his fork and running locally is the only way
