### PR TITLE
Fix: Remove package hint from the section Hints in the documentation

### LINKED ISSUE #935: [bug] The package hint is listed in the documentation as a Hint
image

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #935

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/webhint.io)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

### CODE REVIEW

File: src/webhint-theme/helper/utils.js [hunk 1]
```diff
@@ -15,7 +15,12 @@ const isSectionIndexPage = (page) => {
 };
 
 const isGoodToToC = (page) => {
-    return !isGuideIndexPage(page) && page.tocTitle && page.contentType !== 'hints-category' && page.contentType !== 'hints-index' && page.isMultiHints !== 'true';
+    return !isGuideIndexPage(page) &&
+        page.tocTitle &&
+        page.contentType !== 'hints-category' &&
+        page.contentType !== 'hints-index' &&
+        page.isMultiHints !== 'true' &&
+        page.title !== 'webhint';
```
Comment (antross) [inline src/webhint-theme/helper/utils.js:23]: ❤ the reformatting
