### PR TITLE
Fix: Code formatting.

### LINKED ISSUE #679: Code formatting looks broken in some cases
image

https://webhint.io/docs/contributor-guide/how-to/formatter/

@ststimac can you please take a look?

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #679

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/webhint.io)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -364,8 +364,8 @@ gulp.task('build', gulp.series(
     'build:hexo',
     'copy:robots.txt',
     // 'generate-service-worker',
-    'compress:zopfli',
-    'compress:brotli',
+    // 'compress:zopfli',
```
Comment (molant) [inline gulpfile.js]: I think you forgot to uncomment these lines

Comment (sarvaje) [reply gulpfile.js]: 🤦‍♂️
